### PR TITLE
MAN2-2840 Migrate remaining tests from manager.

### PR DESCRIPTION
**Pull request by rjstires**
- Adds Jest and Enzyme testing.
- Migrates component tests from Manager repo https://github.com/linode/manager/pull/2880

### CODE REVIEW

**Comment by displague** [comment]
Do we need the dist/*spec.js files?

**Comment by rjstires** [comment]
No, I've to exclude then in the build process. No harm, but good eye. Ill get them removed.

**Comment by displague** [comment]
This PR has open conflicts.

**Comment by asauber** [comment]
There are still compiled tests in `dist/`

**Comment by rjstires** [comment]
Nu-uh.

**Comment by displague** [comment]
I see `dist/dropdowns/Dropdown.spec.js`, people.

**Comment by rjstires** [comment]
🤦‍♂️

**Comment by asauber** [comment]
Updated to remove snapshots and add these tests to the Travis config. LGTM

**Review by asauber — APPROVED** [review]

**Pull request merged**
